### ISSUE TITLE
Error with importing SBML file

### ISSUE THREAD

**Issue by max-de-rooij** [sebapersson/SBMLImporter.jl#43]
I'm trying to import the SBML model from [https://www.ebi.ac.uk/biomodels/BIOMD0000000627#Overview](https://www.ebi.ac.uk/biomodels/BIOMD0000000627#Overview). I use the following code:

```julia
using ModelingToolkit
using Downloads
using SBMLImporter

URL = "https://www.ebi.ac.uk/biomodels/model/download/BIOMD0000000627.3?filename=BIOMD0000000627_url.xml"
output = Downloads.download(URL)
mdl, cb = load_SBML(output)
sys = ODESystem(mdl)
```

But I get the following error:

```
ERROR: UndefVarError: `F_in` not defined
Stacktrace:
 [1] top-level scope
   @ none:1
```

Where `F_in` should be one of the variables in the model. 

The SBML file imports fine using a tool like Copasi, so I think it isn't related to the file alone. 

Any idea what is happening here? Or whether I'm doing something wrong? 

Thanks in advance!

**Comment by sebapersson** [comment]
Thanks for reporting!

This is quite subtle, basically SBMLImporter inlines SBML AssignmentRules into the model equations (for faster import), but currently we do not inline AssignmentRules into RateRules. This is a bug I will fix.

As a workaround one can skip he inlining. Now this seems to trigger a bug in ModelingToolkit so I would still recommend the inlining approach.

I think I should be able to have a patch release on this by tomorrow

**Comment by sebapersson** [comment]
#44 should close this issue.

You should when merged be able to load the model with 

```julia
mdl, cb = load_SBML(path_sbml; inline_assignment_rules=false, ifelse_to_callback=true, check_massaction=false)
sys = structural_simplify(convert(ODESystem, mdl.rn))
oprob = ODEProblem(sys, mdl.u₀, tspan, mdl.p, jac=true)
sol = solve(oprob, Rodas5(), callback=cb)
```

Now I have problems to solve the model, mainly I think because of a `log` in the model equations where due to numerical noise certain species can go below zero inside this `log`. If possible I would modify this log-term to be something like `log(... + 1e-10)` or use a picewise with `log(max(..., 0.0))` to never trigger the below zero problems.
