### ISSUE TITLE
Update to ModelingToolkit v9

### ISSUE THREAD

**Issue by sebapersson** [sebapersson/SBMLImporter.jl#45]
When possible should update to use ModelingToolkit v9. However, before this is done Catalyst must update.

**Comment by TorkelE** [comment]
Catalyst update is in progress right now. I think the required MTK PR was merged today, so now it is simply and issue of when we have had time to go through all the code. I don't expect a release before next weekend (and won't suggest that it might be done by then). An April Catalyst release is very much my ambition.

**Comment by sebapersson** [comment]
Thanks for the information! This sounds good, I should have time to then update SBMLImporter in May.
