### ISSUE TITLE
Missing information for remake of ODEProblem

### ISSUE THREAD

**Issue by matthiaskoenig** [sebapersson/SBMLImporter.jl#91]
I want to change initial conditions and parameter values of the loaded problem.
As I understand things I should basically use `remake` on the problem with the things I want to change.
See here: https://docs.sciml.ai/Catalyst/stable/model_simulation/simulation_structure_interfacing/#simulation_structure_interfacing_problems_remake

Model here: [dapagliflozin_intestine.zip](https://github.com/user-attachments/files/18086278/dapagliflozin_intestine.zip)

It looks like the initialization values are not available for remake (probably they have to be correctly created with the problem during the SBML import).
```julia
using SBMLImporter
using Catalyst
using OrdinaryDiffEq
using ModelingToolkit
using Sundials

prn, cb = load_SBML("dapagliflozin_intestine.xml", massaction=false)

tspan = (0.0, 24 * 60.0)
odesys = structural_simplify(convert(ODESystem, prn.rn))
prob = ODEProblem(odesys, prn.u0, tspan, prn.p, jac=true)
tpoints = range(tspan[1], stop=tspan[2], length=1001)

@time begin
sol = solve(
    prob, 
    # Tsit5(), 
    CVODE_BDF(), # Rosenbrock23(), # Tsit5(), # CVODE_BDF
    dense=false, saveat=tpoints)
end

# updating problems using remake: https://docs.sciml.ai/Catalyst/stable/model_simulation/simulation_structure_interfacing/#simulation_structure_interfacing_problems_remake
using OrdinaryDiffEq
prob_new = remake(prob; u0 = [:PODOSE_dap => 10.0])
@time begin
    sol = solve(
        prob_new, 
        # Tsit5(), 
        CVODE_BDF(), # Rosenbrock23(), # Tsit5(), # CVODE_BDF
        dense=false, saveat=tpoints)
end
```

```bash
ERROR: Initialization incomplete. Not all of the state variables of the
DAE system can be determined by the initialization. Missing
variables:

SymbolicUtils.BasicSymbolic{Real}[dap_ext(t), dap_stomach(t), dap_feces(t), Ventero(t), Vlumen(t)]

Stacktrace:
  [1] ModelingToolkit.InitializationProblem{…}(sys::ODESystem, t::Float64, u0map::Dict{…}, parammap::Dict{…}; guesses::Dict{…}, check_length::Bool, warn_initialize_determined::Bool, initialization_eqs::Vector{…}, fully_determined::Nothing, check_units::Bool, use_scc::Bool, kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/Lm8W6/src/systems/diffeqs/abstractodesystem.jl:1341
  [2] InitializationProblem
    @ ~/.julia/packages/ModelingToolkit/Lm8W6/src/systems/diffeqs/abstractodesystem.jl:1295 [inlined]
  [3] #_#1016
    @ ~/.julia/packages/ModelingToolkit/Lm8W6/src/systems/diffeqs/abstractodesystem.jl:1273 [inlined]
  [4] InitializationProblem
    @ ~/.julia/packages/ModelingToolkit/Lm8W6/src/systems/diffeqs/abstractodesystem.jl:1272 [inlined]
  [5] #InitializationProblem#1014
    @ ~/.julia/packages/ModelingToolkit/Lm8W6/src/systems/diffeqs/abstractodesystem.jl:1261 [inlined]
  [6] InitializationProblem
    @ ~/.julia/packages/ModelingToolkit/Lm8W6/src/systems/diffeqs/abstractodesystem.jl:1260 [inlined]
  [7] maybe_build_initialization_problem(sys::ODESystem, op::Dict{…}, u0map::Dict{…}, pmap::Dict{…}, t::Float64, defs::Dict{…}, guesses::Dict{…}, missing_unknowns::Set{…}; implicit_dae::Bool, kwargs::@Kwargs{…})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/Lm8W6/src/systems/problem_utils.jl:545
  [8] remake_initialization_data(sys::ODESystem, odefn::Function, u0::Vector{…}, t0::Float64, p::Missing, newu0::Vector{…}, newp::MTKParameters{…})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/Lm8W6/src/systems/nonlinear/initializesystem.jl:336
  [9] remake_initialization_data_compat_wrapper(sys::ODESystem, scimlfn::Function, u0::Vector{…}, t0::Float64, p::Missing, newu0::Vector{…}, newp::MTKParameters{…})
    @ SciMLBase ~/.julia/packages/SciMLBase/rBKqA/src/remake.jl:234
 [10] remake(prob::ODEProblem{…}; f::Missing, u0::Vector{…}, tspan::Missing, p::Missing, kwargs::Missing, interpret_symbolicmap::Bool, build_initializeprob::Bool, use_defaults::Bool, lazy_initialization::Nothing, _kwargs::@Kwargs{})
    @ SciMLBase ~/.julia/packages/SciMLBase/rBKqA/src/remake.jl:131
 [11] top-level scope
    @ ~/git/vascular_trees.jl/src/sbml/sbml_import2.jl:47
Some type information was truncated. Use `show(err)` to see complete types.
```

Or how else would I change single parameters and initial values on the ODEProblem?

**Comment by sebapersson** [comment]
I would not use `remake` as then you need to change all parameters/states (its more an internal operator used for parameter estimation), rather I would use the symbolic indexing interface:

```julia
using OrdinaryDiffEq, SBMLImporter, ModelingToolkit, Catalyst, Test
path_sbml = joinpath(@__DIR__, "Models", "dapagliflozin_intestine.xml")
prn, cb = load_SBML(path_sbml; massaction = false)
tspan = (0.0, 24 * 60.0)
odesys = structural_simplify(convert(ODESystem, prn.rn))
prob = ODEProblem(odesys, prn.u0, tspan, prn.p, jac=true)
tpoints = range(tspan[1], stop=tspan[2], length=1001)
sol = solve(prob, Rodas5P(), saveat=tpoints)

# For changing initial value
prob[:PODOSE_dap] = 10.0
sol = solve(prob, Rodas5P(), saveat=tpoints)

# For changing parameter
prob.ps[:Mr_dap] = 1.0
```

Where you basically just do `prob[:PODOSE_dap] = 10.0` to change initial value, and p`rob.ps[:Mr_dap] = 1.0` for a parameter value.

Lets keep this issue open, because even though this is more the domain of Catalyst, I think this would be helpful to have in the SBMLImporter documentation. 

Lastly, for solving this small ODE which I guess is stiff, I would use `Rodas5P` (some hints on choosing solver can be found [here](https://sebapersson.github.io/PEtab.jl/stable/default_options/), more extensive discussion will be in the paper on this package once it is published).

**Comment by matthiaskoenig** [comment]
Thanks. This is what I was looking for. 

I am mainly using CVODE_BDF to benchmark against libroadrunner which uses LLVM compilation and CVODE_BDF under the hood. This results in very similar integration times, but the model compilation overhead seems to be larger with julia (i.e. parsing and ODE system generation). It is just a small test system here, but for the larger systems CVODE_BDF seemed to be the fastest option.

**Comment by sebapersson** [comment]
I would say it makes sense that libroadrunner compiles faster (as this takes some time in Julia but only has to be done once per session). 

As for larger ODEs, `CVODE_BDF` often performs well, but I would also test `QNDF`, `FBDF2` and `KenCarp4` as these often also perform well in that regime. For really large models it is also worthwhile to test with sparse jacobian (just set `sparse = true` in the `ODEProblem`)

**Comment by matthiaskoenig** [comment]
I really like the speed of simulation in Julia, but I have some scenarios where I have a lot of different model structures which I basically only simulate once, so compile time really matters here and it would be great to precompile the models (problems) after generation.

Is there any way to store the compiled problem? For the very large models (20 000) the LLVM compilation time goes to 10-30 minutes with roadrunner and I just store the compiled version which then loads in the next session in < 1s. It would be great if I could do something similar with the loaded problem in Julia.

For the large models the SBML overhead is too much and I am thinking about directly writing the reaction systems for these models in Julia, but would need some way to store the compiled versions for fast loading later on.

**Comment by sebapersson** [comment]
I see, this is not an area where Julia currently excels.

Writing the `ReactionSystem` yourself will not improve anything (SBMLImporter.jl overhead is really small, it is actually the JIT compilation of the system itself that takes time). I know that there is quite a lot of work in the community to get compiled binaries for well behaved code (e.g. `ODEProblem`), but generously, this is at least 1 year away.

There is one trick that might work, that is to define your model and first solve call within an precompile-statement in a module https://julialang.github.io/PrecompileTools.jl/stable/. Then loading should be faster (this is the trick most packages use to reduce compile time).

**Comment by matthiaskoenig** [comment]
Thanks. My hope is that JuliaSimCompiler could provide sufficient speedup in addition with other tricks. I am pretty new to Julia. See graph here which shows how poorly the normal compile time performs for larger systems and the speedups with JuliaSimCompiler.
https://youtu.be/OMn9FeVM8NA?t=1667
For medium size systems I have currently Julia compile times of ~5 - 10 hours ;) and looking urgently for solutions to make this work. From the graph it looks like this could bring down compile times to ~20-30 min for systems with 100.000 equations.

**Comment by matthiaskoenig** [comment]
Thanks. Great tips.

Unfortunately JuliaSimCompiler is not working for us because it prohibits commercial use or possible medical applications in the future. The licensing is very problematic for us. 
JuliaSimCompiler is all part of the commerical JuliaHub but not available as open source solution. It seems not possible to build larger model with ModelingToolkit in Julia in the OpenSource version. The reason why we want to use Julia is because it is OpenSource, but it seems that a lot is available only via the JuliaHub (which would be a licensing model analogue to Matlab or Mathematica, only that we also have to pay for the compute time in addition?!)

I am really confused here, because it seems that a lot of the important developments in the language are only happening in the commercial JuliaHub and one has to wait that an OpenSource port/library with the same functionality will be made available in the future. 

So it seems larger models are difficult with the ModelingToolkit in the open version of Julia. We have some alternative ideas to solve the compilation issues.

**Comment by sebapersson** [comment]
Sorry to hear about the license on JuliaSimCompiler. I would say that the Compiler is the only major thing provided by JuliaHub which is not open source that is needed for classical workflows in SysBio (the other things are not open source are for modeling circuits, and NLME PKPD models, but NLME PKPD is regardless of tool something that is not open source). Anyhow, I agree that ModelingToolkit  at the current stage is not ideal for large models (at least if one loads and compile models frequently, when they fix static compilation things might be different as one only has to compile once).

There is one last thing you can try. For working with SciML models, I recently added import of `ODEProblem` directly in Julia. In this approach I never work with ModelingToolkit, and I do not think the performance penalty is large in this case from skipping symbolic pre-processing. This feature is not part of the public API as I use it only for PEtab.jl, but you can find details here https://github.com/sebapersson/SBMLImporter.jl/blob/main/test/odeproblem_import.jl. Basically you import the problem with:

```julia
using SBMLImporter
model_SBML = SBMLImporter.parse_SBML(path_SBML, false; model_as_string = false, inline_assignment_rules=true)
model_SBML_prob = SBMLImporter.ModelSBMLProb(model_SBML)
oprob2, compute_u0, cb2 = SBMLImporter._get_odeproblem(model_SBML_prob, model_SBML)
oprob2.u0 .= compute_u0(oprob2.p, 0.0)
sol2 = solve(oprob2, Rodas5P(), abstol = 1e-10, reltol = 1e-10, saveat = 1:10, callback = cb2)
```

If this is helpful I can add a function to directly import as `ODEProblem`.

**Comment by sebapersson** [comment]
I am closing this as I have now updated the tutorial with some tips on how to work with an imported model (#92). 

If you want to further discuss the import of larger models (which you hopefully will find a good solution for :), feel free to continue it here, or open a separate issue.
